{"Python UnicodeDecodeError - Am I misunderstanding encode?": 4}